# profile = real 인 설정파일
# RDS 환경 구성

spring:
  profiles:
    include: real-db # 후에 추가
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  session:
    store-type: jdbc

  boot:
    admin:
      client:
        url: http://127.0.0.1:9090
        instance:
          # server-url: http://127.0.0.1:8080
          service-base-url: http://127.0.0.1:8080