spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "developoffi@gmail.com"
    password: "gkdtksgkdtla9921"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true